In [18]:
from numbers import Number
import numpy as np
import pandas as pd
import qutip as q
import matplotlib.pyplot as plt
import onix.models.hyperfine as hyperfine
from IPython.display import display

%matplotlib ipympl

In [81]:

hyperfine.set_magnetic_site(sigma_positive=False, pi_positive=True, verbose=True)
np.round(hyperfine.quadrupole_tensor_D["7F0"], 2)

Sigma = -1, Pi = +1


array([[ -7.65,  -6.25, -17.45],
       [ -6.25, -10.96,  -6.41],
       [-17.45,  -6.41, -13.4 ]])

In [72]:
B_field = [225e-4, 0, 6e-4]
hyperfine.set_magnetic_site(sigma_positive=True, pi_positive=True, verbose=True)
g_sp_pp = hyperfine.HyperfineStates(
    hyperfine.state_labels["7F0"], hyperfine.quadrupole_tensor_D["7F0"], hyperfine.Zeeman_tensor_D["7F0"],
    B_field, positive_sigma = True,
)
print(g_sp_pp._quadrupole_tensor)
print(g_sp_pp._Zeeman_tensor)
print()
hyperfine.set_magnetic_site(sigma_positive=False, pi_positive=True, verbose=True)
g_sm_pp = hyperfine.HyperfineStates(
    hyperfine.state_labels["7F0"], hyperfine.quadrupole_tensor_D["7F0"], hyperfine.Zeeman_tensor_D["7F0"],
    B_field, positive_sigma = False,
)
print(g_sm_pp._quadrupole_tensor)
print(g_sm_pp._Zeeman_tensor)
print()
hyperfine.set_magnetic_site(sigma_positive=True, pi_positive=False, verbose=True)
g_sp_pm = hyperfine.HyperfineStates(
    hyperfine.state_labels["7F0"], hyperfine.quadrupole_tensor_D["7F0"], hyperfine.Zeeman_tensor_D["7F0"],
    B_field, positive_sigma = True,
)
print(g_sp_pp._quadrupole_tensor)
print(g_sp_pp._Zeeman_tensor)
print()
hyperfine.set_magnetic_site(sigma_positive=False, pi_positive=False, verbose=True)
g_sm_pm = hyperfine.HyperfineStates(
    hyperfine.state_labels["7F0"], hyperfine.quadrupole_tensor_D["7F0"], hyperfine.Zeeman_tensor_D["7F0"],
    B_field, positive_sigma = False,
)
print(g_sm_pm._quadrupole_tensor)
print(g_sm_pm._Zeeman_tensor)

Sigma = +1, Pi = +1
[[ -7.64508919  -6.24673043  17.4521336 ]
 [ -6.24673043 -10.95556664   6.40942889]
 [ 17.4521336    6.40942889 -13.39934417]]
[[ 1.68085996 -0.40933951 -2.08553937]
 [-0.40933951  1.47490928 -1.68152536]
 [-2.08553937 -1.68152536 -3.61127843]]

Sigma = -1, Pi = +1
[[ -7.64508919  -6.24673043 -17.4521336 ]
 [ -6.24673043 -10.95556664  -6.40942889]
 [-17.4521336   -6.40942889 -13.39934417]]
[[ 1.68085996 -0.40933951  2.08553937]
 [-0.40933951  1.47490928  1.68152536]
 [ 2.08553937  1.68152536 -3.61127843]]

Sigma = +1, Pi = -1
[[ -7.64508919  -6.24673043  17.4521336 ]
 [ -6.24673043 -10.95556664   6.40942889]
 [ 17.4521336    6.40942889 -13.39934417]]
[[ 1.68085996 -0.40933951 -2.08553937]
 [-0.40933951  1.47490928 -1.68152536]
 [-2.08553937 -1.68152536 -3.61127843]]

Sigma = -1, Pi = -1
[[ -7.64508919  -6.24673043 -17.4521336 ]
 [ -6.24673043 -10.95556664  -6.40942889]
 [-17.4521336   -6.40942889 -13.39934417]]
[[ 1.68085996 -0.40933951  2.08553937]
 [-0.40933951  1

In [73]:
g_sp_pp.H_quadrupole() - g_sm_pp.H_quadrupole()

Quantum object: dims=[[6], [6]], shape=(6, 6), type='oper', dtype=Dense, isherm=True
Qobj data =
[[ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00
   0.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  3.55271368e-15
   0.00000000e+00  0.00000000e+00]
 [ 1.77635684e-15  0.00000000e+00 -1.42108547e-14 -5.88696493e-16
   7.10542736e-15  0.00000000e+00]
 [ 0.00000000e+00  7.10542736e-15  5.88696493e-16 -1.42108547e-14
   0.00000000e+00  1.77635684e-15]
 [ 0.00000000e+00  0.00000000e+00  3.55271368e-15  0.00000000e+00
   0.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00
   0.00000000e+00  0.00000000e+00]]

In [35]:
g_sp_pp._Hamiltonian.eigenstates()[0]

array([-202.754568  , -202.754568  ,  -83.62050231,  -83.62050231,
          6.37507031,    6.37507031])

In [36]:
g_sm_pp._Hamiltonian.eigenstates()[0]

array([-202.754568  , -202.754568  ,  -83.62050231,  -83.62050231,
          6.37507031,    6.37507031])

In [29]:
g_sp_pp.energies_and_eigenstates()[1][0]

Quantum object: dims=[[6], [1]], shape=(6, 1), type='ket', dtype=Dense
Qobj data =
[[ 0.        +0.j        ]
 [-0.03552699-0.0004894j ]
 [-0.01143247-0.14410784j]
 [ 0.31232708-0.18745131j]
 [ 0.66419252+0.05824373j]
 [ 0.54551863+0.32096575j]]

In [30]:
g_sm_pp.energies_and_eigenstates()[1][0]

Quantum object: dims=[[6], [1]], shape=(6, 1), type='ket', dtype=Dense
Qobj data =
[[ 0.63293727+0.j        ]
 [-0.60199273-0.28661609j]
 [ 0.17413225+0.31994399j]
 [ 0.0829313 -0.11840681j]
 [-0.03086833-0.01759412j]
 [ 0.        +0.j        ]]

In [74]:
state = g_sp_pp.energies_and_eigenstates()[1][3]
print(q.expect(g_sp_pp.H_Zeeman([225e-4, 0, 0]), state))
print(q.expect(g_sm_pp.H_Zeeman([225e-4, 0, 0]), state))

print(q.expect(g_sp_pp.H_Zeeman([225e-4, 0, 6e-4]), state))
print(q.expect(g_sm_pp.H_Zeeman([225e-4, 0, 6e-4]), state))

print(q.expect(g_sp_pp._I_x, state))
print(q.expect(g_sm_pp._I_x, state))

0.07095948663390098
-0.07095948663390098
0.07203513459883933
-0.06988383866896264
0.7306290917838867
-0.7306290917838867


In [75]:
state = g_sp_pp.energies_and_eigenstates()[1][2]
print(q.expect(g_sp_pp.H_Zeeman([225e-4, 0, 0]), state))
print(q.expect(g_sm_pp.H_Zeeman([225e-4, 0, 0]), state))

print(q.expect(g_sp_pp.H_Zeeman([225e-4, 0, 6e-4]), state))
print(q.expect(g_sm_pp.H_Zeeman([225e-4, 0, 6e-4]), state))

print(q.expect(g_sp_pp._I_x, state))
print(q.expect(g_sm_pp._I_x, state))

-0.07105605865634748
0.07105605865634748
-0.07213382453518005
0.06997829277751488
-0.7315726163618608
0.7315726163618609


In [4]:
g_sp_pp._I_x.full() @ g_sp_pp._quadrupole_tensor @ g_sp_pp._I_x.dag().full()

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 3 is different from 6)

In [38]:
g_sp_pp.energies_and_eigenstates()[1][0]

Quantum object: dims=[[6], [1]], shape=(6, 1), type='ket', dtype=Dense
Qobj data =
[[-0.63291787-0.j        ]
 [ 0.60162786+0.28704036j]
 [-0.1771092 -0.32064474j]
 [-0.08360817+0.11081813j]
 [ 0.03758818+0.00532288j]
 [ 0.01070678-0.00769304j]]

In [36]:
g_sp_pp.energies_and_eigenstates()[1][2]

Quantum object: dims=[[6], [1]], shape=(6, 1), type='ket', dtype=Dense
Qobj data =
[[ 0.54206131+0.j        ]
 [ 0.00067695+0.16833882j]
 [-0.52288066-0.53446692j]
 [ 0.02749503+0.26403748j]
 [ 0.11498949-0.00135119j]
 [-0.15739727-0.10149856j]]

In [35]:
g_sm_pp.energies_and_eigenstates()[1][3]

Quantum object: dims=[[6], [1]], shape=(6, 1), type='ket', dtype=Dense
Qobj data =
[[ 5.41814520e-01+0.j        ]
 [ 2.71155919e-04-0.16805994j]
 [-5.22179912e-01-0.53534227j]
 [-2.66549501e-02-0.26389365j]
 [ 1.15782720e-01-0.00080514j]
 [ 1.57498988e-01+0.10181865j]]

In [63]:
def print_mu_and_I(state, sigma_positive, pi_positive, n=2):
    print_statement = "Sigma = "
    if sigma_positive:
        print_statement += "+1"
    else:
        print_statement += "-1"
    print_statement += ", Pi = "
    if pi_positive:
        print_statement += "+1"
    else:
        print_statement += "-1"
    print(print_statement)
    b_index = 3
    e, s = state.energies_and_eigenstates()
    print(
        "mu_i = ",
        round(state.mu_Ix(s[b_index]), n),
        round(state.mu_Iy(s[b_index]), n),
        round(state.mu_Iz(s[b_index]), n)
    )
    print(
        "I_i = ",
        round(state.m_Ix(s[b_index]), n),
        round(state.m_Iy(s[b_index]), n),
        round(state.m_Iz(s[b_index]), n)
    )
    if pi_positive:
        n_x = 1
    else:
        n_x = -1
    print(
        "n_x = ",
        n_x
    )
    print(
        "I.n = ",
        round(state.m_Ix(s[b_index]), n) * n_x
    )

In [64]:
def simulate(B_field):
    hyperfine.set_magnetic_site(sigma_positive=True, pi_positive=True, verbose=False)
    g_sp_pp = hyperfine.HyperfineStates(
        hyperfine.state_labels["7F0"], hyperfine.quadrupole_tensor_D["7F0"], hyperfine.Zeeman_tensor_D["7F0"],
    B_field, positive_sigma = True,
    )
    hyperfine.set_magnetic_site(sigma_positive=False, pi_positive=True, verbose=False)
    g_sm_pp = hyperfine.HyperfineStates(
        hyperfine.state_labels["7F0"], hyperfine.quadrupole_tensor_D["7F0"], hyperfine.Zeeman_tensor_D["7F0"],
    B_field, positive_sigma = False,
    )
    hyperfine.set_magnetic_site(sigma_positive=True, pi_positive=False, verbose=False)
    g_sp_pm = hyperfine.HyperfineStates(
        hyperfine.state_labels["7F0"], hyperfine.quadrupole_tensor_D["7F0"], hyperfine.Zeeman_tensor_D["7F0"],
    B_field, positive_sigma = True,
    )
    hyperfine.set_magnetic_site(sigma_positive=False, pi_positive=False, verbose=False)
    g_sm_pm = hyperfine.HyperfineStates(
        hyperfine.state_labels["7F0"], hyperfine.quadrupole_tensor_D["7F0"], hyperfine.Zeeman_tensor_D["7F0"],
    B_field, positive_sigma = False,
    )
    print_mu_and_I(g_sp_pp, True, True)
    print()
    print_mu_and_I(g_sm_pp, False, True)
    print()
    print_mu_and_I(g_sp_pm, True, False)
    print()
    print_mu_and_I(g_sm_pm, False, False)

In [65]:
B_field = [223e-4, 0e-4, 0e-4]
simulate(B_field)

Sigma = +1, Pi = +1
mu_i =  -0.41 -0.17 -0.22
I_i =  0.75 0.03 -0.91
n_x =  1
I.n =  0.75

Sigma = -1, Pi = +1
mu_i =  -0.41 -0.17 0.22
I_i =  0.75 0.03 0.91
n_x =  1
I.n =  0.75

Sigma = +1, Pi = -1
mu_i =  -0.41 -0.17 -0.22
I_i =  0.75 0.03 -0.91
n_x =  -1
I.n =  -0.75

Sigma = -1, Pi = -1
mu_i =  -0.41 -0.17 0.22
I_i =  0.75 0.03 0.91
n_x =  -1
I.n =  -0.75


In [29]:
B_field = [0e-4, 0e-4, 100e-4]
simulate(B_field)

Sigma = +1, Pi = +1
mu_i =  -0.17 -0.12 -0.54
I_i =  -0.32 -0.36 -0.8
n_x =  1
I.n =  -0.32

Sigma = -1, Pi = +1
mu_i =  0.17 0.12 -0.54
I_i =  0.32 0.36 -0.8
n_x =  1
I.n =  0.32

Sigma = +1, Pi = -1
mu_i =  -0.17 -0.12 -0.54
I_i =  -0.32 -0.36 -0.8
n_x =  -1
I.n =  0.32

Sigma = -1, Pi = -1
mu_i =  0.17 0.12 -0.54
I_i =  0.32 0.36 -0.8
n_x =  -1
I.n =  -0.32


In [30]:
B_field = [223e-4, 0e-4, 100e-4]
simulate(B_field)

Sigma = +1, Pi = +1
mu_i =  -0.38 -0.18 -0.4
I_i =  0.42 -0.14 -1.02
n_x =  1
I.n =  0.42

Sigma = -1, Pi = +1
mu_i =  -0.34 -0.1 -0.11
I_i =  1.01 0.26 0.48
n_x =  1
I.n =  1.01

Sigma = +1, Pi = -1
mu_i =  -0.38 -0.18 -0.4
I_i =  0.42 -0.14 -1.02
n_x =  -1
I.n =  -0.42

Sigma = -1, Pi = -1
mu_i =  -0.34 -0.1 -0.11
I_i =  1.01 0.26 0.48
n_x =  -1
I.n =  -1.01
