In [5]:
import numpy as np
import cProfile

In [79]:
def data_averaging(data, sample_rate, pulse_times):
    """Averages digitizer data based on time intervals.

    Args:
        data: np.array, must be 2-dimensional. The first dimension is repeats (segments).
            The second dimension is time indices.
        sample_rate: float, sample rate per second.
        pulse_times: list of 2-tuples, time intervals to average the data at.

    Returns:
        (data_avg, data_err)
        Both data_avg and data_err has the first dimension as repeats,
        and the second dimension as time interval indices (same length as pulse_times).
    """
    if not isinstance(data, np.ndarray):
        data = np.array(data)
    if not (data.ndim == 2):
        raise ValueError("The input data must be 2-dimensional")

    data_avg = []
    data_err = []

    pulse_times = (np.array(pulse_times) * sample_rate).astype(int)
    for kk in range(len(pulse_times)):
        data_temp = data[:, pulse_times[kk][0]: pulse_times[kk][1]]
        scans_avg = np.average(data_temp, axis=1)
        scans_err = np.std(data_temp, axis=1) / np.sqrt(pulse_times[kk][1] - pulse_times[kk][0])
        data_avg.append(scans_avg)
        data_err.append(scans_err)

    return np.transpose(data_avg), np.transpose(data_err)


In [80]:
sample_rate = 25e6
pulse_times = [(kk * 10 / sample_rate, (kk * 10 + 8) / sample_rate) for kk in range(100)]
data = np.random.rand(1000, int(np.max(pulse_times) * sample_rate) + 1000)
data2 = [np.random.rand(1000, int(np.max(pulse_times) * sample_rate) + 1000) for kk in range(2)]

In [81]:
data_averaging(data, sample_rate, pulse_times)

(array([[0.44142812, 0.39953061, 0.53251207, ..., 0.49923584, 0.54772942,
         0.44087253],
        [0.4031101 , 0.47714005, 0.41360519, ..., 0.46642151, 0.50808245,
         0.46649804],
        [0.39746948, 0.49494637, 0.49663785, ..., 0.54633892, 0.42768751,
         0.54443012],
        ...,
        [0.48150257, 0.49930337, 0.54209152, ..., 0.46307346, 0.56897411,
         0.65491443],
        [0.7195301 , 0.55267886, 0.39912395, ..., 0.57313944, 0.47690815,
         0.655369  ],
        [0.33367738, 0.65605285, 0.49003855, ..., 0.53451874, 0.58926763,
         0.34811133]]),
 array([[0.09329384, 0.1123399 , 0.10408813, ..., 0.06603429, 0.10943042,
         0.11606133],
        [0.06080927, 0.11425919, 0.06710894, ..., 0.11009508, 0.10704043,
         0.08547254],
        [0.10183091, 0.08863859, 0.07349172, ..., 0.1209623 , 0.09652165,
         0.09725247],
        ...,
        [0.08573186, 0.09594008, 0.10579871, ..., 0.06313389, 0.09417186,
         0.12093708],
        [0.0

In [84]:
a = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])

In [87]:
a.reshape(a.shape[0] * a.shape[1], *a.shape[2:])

array([1, 2, 3, 4])

In [86]:
a = np.array([[1,2], [3,4]])